# Generated by Django 3.1.4 on 2021-06-18 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_auto_20210607_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=6)),
                ('load', models.PositiveSmallIntegerField()),
                ('like', models.PositiveSmallIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='calification',
            index=models.Index(fields=['course', 'period'], name='courses_cal_course__49720c_idx'),
        ),
        migrations.AddIndex(
            model_name='calification',
            index=models.Index(fields=['user', 'period'], name='courses_cal_user_id_7c8603_idx'),
        ),
    ]
