# Generated by Django 3.2.5 on 2021-07-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses_calification", "0002_alter_calification_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="calification",
            name="communication",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calification",
            name="online_adaptation",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
