# Generated by Django 3.2.5 on 2022-01-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses_calification", "0005_calification_difficulty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calification",
            name="like",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="calification",
            name="load",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
