# Generated by Django 3.2.5 on 2022-01-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses_calification", "0006_auto_20220101_1328"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calification",
            name="comment",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
