# Generated by Django 3.1.4 on 2020-12-19 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('credits', models.PositiveSmallIntegerField()),
                ('req', models.TextField(blank=True, max_length=1000, null=True)),
                ('con', models.CharField(blank=True, max_length=16, null=True)),
                ('restr', models.TextField(blank=True, max_length=1000, null=True)),
                ('program', models.TextField(blank=True, null=True)),
                ('school', models.CharField(blank=True, max_length=32, null=True)),
                ('area', models.CharField(blank=True, max_length=32, null=True)),
                ('category', models.CharField(blank=True, max_length=64, null=True)),
                ('categories', models.ManyToManyField(to='courses.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=6)),
                ('section', models.PositiveSmallIntegerField()),
                ('nrc', models.CharField(blank=True, max_length=10, null=True)),
                ('teachers', models.CharField(blank=True, max_length=1000, null=True)),
                ('schedule', models.CharField(blank=True, max_length=255, null=True)),
                ('format', models.CharField(blank=True, max_length=16, null=True)),
                ('campus', models.CharField(blank=True, max_length=32, null=True)),
                ('is_english', models.BooleanField()),
                ('is_removable', models.BooleanField()),
                ('is_special', models.BooleanField()),
                ('available_quota', models.SmallIntegerField(blank=True, null=True)),
                ('total_quota', models.SmallIntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='FullSchedule',
            fields=[
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='courses.section')),
                ('l1', models.CharField(default='FREE', max_length=4)),
                ('l2', models.CharField(default='FREE', max_length=4)),
                ('l3', models.CharField(default='FREE', max_length=4)),
                ('l4', models.CharField(default='FREE', max_length=4)),
                ('l5', models.CharField(default='FREE', max_length=4)),
                ('l6', models.CharField(default='FREE', max_length=4)),
                ('l7', models.CharField(default='FREE', max_length=4)),
                ('l8', models.CharField(default='FREE', max_length=4)),
                ('m1', models.CharField(default='FREE', max_length=4)),
                ('m2', models.CharField(default='FREE', max_length=4)),
                ('m3', models.CharField(default='FREE', max_length=4)),
                ('m4', models.CharField(default='FREE', max_length=4)),
                ('m5', models.CharField(default='FREE', max_length=4)),
                ('m6', models.CharField(default='FREE', max_length=4)),
                ('m7', models.CharField(default='FREE', max_length=4)),
                ('m8', models.CharField(default='FREE', max_length=4)),
                ('w1', models.CharField(default='FREE', max_length=4)),
                ('w2', models.CharField(default='FREE', max_length=4)),
                ('w3', models.CharField(default='FREE', max_length=4)),
                ('w4', models.CharField(default='FREE', max_length=4)),
                ('w5', models.CharField(default='FREE', max_length=4)),
                ('w6', models.CharField(default='FREE', max_length=4)),
                ('w7', models.CharField(default='FREE', max_length=4)),
                ('w8', models.CharField(default='FREE', max_length=4)),
                ('j1', models.CharField(default='FREE', max_length=4)),
                ('j2', models.CharField(default='FREE', max_length=4)),
                ('j3', models.CharField(default='FREE', max_length=4)),
                ('j4', models.CharField(default='FREE', max_length=4)),
                ('j5', models.CharField(default='FREE', max_length=4)),
                ('j6', models.CharField(default='FREE', max_length=4)),
                ('j7', models.CharField(default='FREE', max_length=4)),
                ('j8', models.CharField(default='FREE', max_length=4)),
                ('v1', models.CharField(default='FREE', max_length=4)),
                ('v2', models.CharField(default='FREE', max_length=4)),
                ('v3', models.CharField(default='FREE', max_length=4)),
                ('v4', models.CharField(default='FREE', max_length=4)),
                ('v5', models.CharField(default='FREE', max_length=4)),
                ('v6', models.CharField(default='FREE', max_length=4)),
                ('v7', models.CharField(default='FREE', max_length=4)),
                ('v8', models.CharField(default='FREE', max_length=4)),
                ('s1', models.CharField(default='FREE', max_length=4)),
                ('s2', models.CharField(default='FREE', max_length=4)),
                ('s3', models.CharField(default='FREE', max_length=4)),
                ('s4', models.CharField(default='FREE', max_length=4)),
                ('s5', models.CharField(default='FREE', max_length=4)),
                ('s6', models.CharField(default='FREE', max_length=4)),
                ('s7', models.CharField(default='FREE', max_length=4)),
                ('s8', models.CharField(default='FREE', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleInfo',
            fields=[
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='courses.section')),
                ('total', models.IntegerField(blank=True, null=True)),
                ('ayu', models.IntegerField(blank=True, null=True)),
                ('clas', models.IntegerField(blank=True, null=True)),
                ('lab', models.IntegerField(blank=True, null=True)),
                ('pra', models.IntegerField(blank=True, null=True)),
                ('sup', models.IntegerField(blank=True, null=True)),
                ('tal', models.IntegerField(blank=True, null=True)),
                ('ter', models.IntegerField(blank=True, null=True)),
                ('tes', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('category', models.CharField(max_length=255)),
                ('quota', models.IntegerField(blank=True, null=True)),
                ('banner', models.CharField(blank=True, max_length=32, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.section')),
            ],
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['period', 'course'], name='courses_sec_period_b201a6_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['course', 'section'], name='courses_sec_course__784d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['campus'], name='courses_sec_campus_7f80b8_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['available_quota'], name='courses_sec_availab_72ac76_idx'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('period', 'course', 'section'), name='period_section'),
        ),
        migrations.AddIndex(
            model_name='scheduleinfo',
            index=models.Index(fields=['total'], name='courses_sch_total_4ec1be_idx'),
        ),
        migrations.AddIndex(
            model_name='quota',
            index=models.Index(fields=['section_id', 'date'], name='courses_quo_section_e01ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['req'], name='courses_cou_req_aa456d_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['school'], name='courses_cou_school_742ea4_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['area'], name='courses_cou_area_e7795f_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category'], name='courses_cou_categor_fec4a4_idx'),
        ),
    ]
