# Generated by Django 3.1.4 on 2021-06-07 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="categories",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
