# Generated by Django 3.2.4 on 2021-07-03 17:15

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_auto_20210624_0435"),
    ]

    operations = [
        UnaccentExtension(),
    ]
