# Generated by Django 3.2.16 on 2023-07-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_auto_20210703_1715"),
    ]

    operations = [
        migrations.AddField(
            model_name="fullschedule",
            name="j9",
            field=models.CharField(default="FREE", max_length=4),
        ),
        migrations.AddField(
            model_name="fullschedule",
            name="l9",
            field=models.CharField(default="FREE", max_length=4),
        ),
        migrations.AddField(
            model_name="fullschedule",
            name="m9",
            field=models.CharField(default="FREE", max_length=4),
        ),
        migrations.AddField(
            model_name="fullschedule",
            name="s9",
            field=models.CharField(default="FREE", max_length=4),
        ),
        migrations.AddField(
            model_name="fullschedule",
            name="v9",
            field=models.CharField(default="FREE", max_length=4),
        ),
        migrations.AddField(
            model_name="fullschedule",
            name="w9",
            field=models.CharField(default="FREE", max_length=4),
        ),
    ]
