# Generated by Django 3.1.4 on 2021-06-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="message",
            field=models.CharField(max_length=1500),
        ),
    ]
