from django.db import models
from .section import Section


class FullSchedule(models.Model):
    section = models.OneToOneField(Section, on_delete=models.CASCADE, primary_key=True)
    l1 = models.CharField(max_length=4, default="FREE")
    l2 = models.CharField(max_length=4, default="FREE")
    l3 = models.CharField(max_length=4, default="FREE")
    l4 = models.CharField(max_length=4, default="FREE")
    l5 = models.CharField(max_length=4, default="FREE")
    l6 = models.CharField(max_length=4, default="FREE")
    l7 = models.CharField(max_length=4, default="FREE")
    l8 = models.CharField(max_length=4, default="FREE")
    l9 = models.CharField(max_length=4, default="FREE")
    m1 = models.CharField(max_length=4, default="FREE")
    m2 = models.CharField(max_length=4, default="FREE")
    m3 = models.CharField(max_length=4, default="FREE")
    m4 = models.CharField(max_length=4, default="FREE")
    m5 = models.CharField(max_length=4, default="FREE")
    m6 = models.CharField(max_length=4, default="FREE")
    m7 = models.CharField(max_length=4, default="FREE")
    m8 = models.CharField(max_length=4, default="FREE")
    m9 = models.CharField(max_length=4, default="FREE")
    w1 = models.CharField(max_length=4, default="FREE")
    w2 = models.CharField(max_length=4, default="FREE")
    w3 = models.CharField(max_length=4, default="FREE")
    w4 = models.CharField(max_length=4, default="FREE")
    w5 = models.CharField(max_length=4, default="FREE")
    w6 = models.CharField(max_length=4, default="FREE")
    w7 = models.CharField(max_length=4, default="FREE")
    w8 = models.CharField(max_length=4, default="FREE")
    w9 = models.CharField(max_length=4, default="FREE")
    j1 = models.CharField(max_length=4, default="FREE")
    j2 = models.CharField(max_length=4, default="FREE")
    j3 = models.CharField(max_length=4, default="FREE")
    j4 = models.CharField(max_length=4, default="FREE")
    j5 = models.CharField(max_length=4, default="FREE")
    j6 = models.CharField(max_length=4, default="FREE")
    j7 = models.CharField(max_length=4, default="FREE")
    j8 = models.CharField(max_length=4, default="FREE")
    j9 = models.CharField(max_length=4, default="FREE")
    v1 = models.CharField(max_length=4, default="FREE")
    v2 = models.CharField(max_length=4, default="FREE")
    v3 = models.CharField(max_length=4, default="FREE")
    v4 = models.CharField(max_length=4, default="FREE")
    v5 = models.CharField(max_length=4, default="FREE")
    v6 = models.CharField(max_length=4, default="FREE")
    v7 = models.CharField(max_length=4, default="FREE")
    v8 = models.CharField(max_length=4, default="FREE")
    v9 = models.CharField(max_length=4, default="FREE")
    s1 = models.CharField(max_length=4, default="FREE")
    s2 = models.CharField(max_length=4, default="FREE")
    s3 = models.CharField(max_length=4, default="FREE")
    s4 = models.CharField(max_length=4, default="FREE")
    s5 = models.CharField(max_length=4, default="FREE")
    s6 = models.CharField(max_length=4, default="FREE")
    s7 = models.CharField(max_length=4, default="FREE")
    s8 = models.CharField(max_length=4, default="FREE")
    s9 = models.CharField(max_length=4, default="FREE")


class ScheduleInfo(models.Model):
    section = models.OneToOneField(Section, on_delete=models.CASCADE, primary_key=True)
    total = models.IntegerField(blank=True, null=True)
    ayu = models.IntegerField(blank=True, null=True)
    clas = models.IntegerField(blank=True, null=True)
    lab = models.IntegerField(blank=True, null=True)
    pra = models.IntegerField(blank=True, null=True)
    sup = models.IntegerField(blank=True, null=True)
    tal = models.IntegerField(blank=True, null=True)
    ter = models.IntegerField(blank=True, null=True)
    tes = models.IntegerField(blank=True, null=True)

    class Meta:
        indexes = [
            models.Index(fields=["total"]),
        ]
